### Dealing with Duplicate values, missing data

In [26]:
import pandas as pd
import numpy as np

### Duplicate Values

In [3]:
cdata = pd.read_csv("subdata_pandas/company.csv")
cdata

    EEID      Name gender   salary
0  EMP01    ayushi      F      NaN
1  EMP02     rohit      M  25000.0
2  EMP03  pranjali    NaN  27000.0
3  EMP01    ayushi      F  20000.0
4  EMP05       NaN      M  25000.0
5  EMP06     rohit      M      NaN
6  EMP02     rohit      M  25000.0

In [ ]:
#Overall duplicate
cdata.duplicated() #Boolean
cdata[cdata.duplicated()]  #Select row

#Based on
cdata['EEID'].duplicated()  #Boolean
cdata[cdata['EEID'].duplicated()]

cdata.drop_duplicates()
cdata['EEID'].drop_duplicates()

0    EMP01
1    EMP02
2    EMP03
4    EMP05
5    EMP06
Name: EEID, dtype: object

### Missing Data

In [34]:
cdata = pd.read_csv("subdata_pandas/company.csv")
cdata

    EEID      Name gender   salary
0  EMP01    ayushi      F      NaN
1  EMP02     rohit      M  25000.0
2  EMP03  pranjali    NaN  27000.0
3  EMP01    ayushi      F  20000.0
4  EMP05       NaN      M  25000.0
5  EMP06     rohit      M      NaN
6  EMP02     rohit      M  25000.0

In [ ]:
#Check null
cdata.isnull()
#Employee
edata = pd.read_csv("subdata_pandas/employee.csv")
edata.isnull().sum()

edata['salary'].isnull().sum()
#Eliminate Nan rows
cdata.dropna()

,id,gender,dateofbirth,education,department,salary,starting_salary,job_time,previous_experience,minority
1,2,Male,23-05-1958,16,IT,40200,18750,8.17,3.00,No
2,3,Female,26-07-1929,12,Finance,21450,12000,8.17,31.75,No
3,4,Female,15-04-1947,18,IT,21900,13200,8.17,15.83,No
4,5,Male,09-02-1955,15,Finance,45000,21000,8.17,11.50,No
5,6,Male,22-08-1958,15,Sales,32100,13500,8.17,5.58,No
...,...,...,...,...,...,...,...,...,...,...
469,470,Male,22-01-1964,12,IT,26250,15750,5.33,5.75,Yes
470,471,Male,03-08-1966,15,Engineering,26400,15750,5.33,2.67,Yes
471,472,Male,21-02-1966,15,Sales,39150,15750,5.25,3.83,No
472,473,Female,25-11-1937,12,Marketing,21450,12750,5.25,11.58,No
473,474,Female,05-11-1968,12,IT,29400,14250,5.25,0.75,No

In [39]:
#Replace NaN with any value
cdata.replace(np.nan,"Insufficient")

#Replace NaN with 30000 in salary
cdata['salary'].replace(np.nan,3000)

#Replace NaN salary with avg
mean = np.mean(cdata['salary'])
mean

#M1
cdata['salary'].replace(np.nan,mean)

#M2
cdata['salary']= cdata['salary'].fillna(mean)
cdata

    EEID      Name gender   salary
0  EMP01    ayushi      F  24400.0
1  EMP02     rohit      M  25000.0
2  EMP03  pranjali    NaN  27000.0
3  EMP01    ayushi      F  20000.0
4  EMP05       NaN      M  25000.0
5  EMP06     rohit      M  24400.0
6  EMP02     rohit      M  25000.0

In [45]:
cdata = pd.read_csv("subdata_pandas/company.csv")
cdata

# Forword fill (Previous row)
cdata.ffill()

# Backword fill (Next row)
cdata.bfill()

#Save it
cdata.bfill(inplace=True)
cdata

cdata['salary']=cdata['salary'].bfill()
cdata

    EEID      Name gender   salary
0  EMP01    ayushi      F  25000.0
1  EMP02     rohit      M  25000.0
2  EMP03  pranjali      F  27000.0
3  EMP01    ayushi      F  20000.0
4  EMP05     rohit      M  25000.0
5  EMP06     rohit      M  25000.0
6  EMP02     rohit      M  25000.0