### GroupBy, MergeOrJoin

In [1]:
import pandas as pd

In [3]:
exp = pd.read_excel("subdata_pandas/expense (1).xlsx")
exp

         Date    Category       Sub-Category   Amount Payment Mode
0  2023-01-01     Grocery             Grocery      30         Cash
1  2023-01-02        Food          Restaurant     890          UPI
2  2023-01-04        Food              Zomato     257         Cash
3  2023-01-06  Essentials               Diary     120          UPI
4  2023-01-06  Essentials             Perfume    1500         Cash
5  2023-01-09     Grocery  Fruits and Veggies     456         Cash
6  2023-01-10       Bills          House Rent   16000         Card
7  2023-01-10     Grocery      Tomato KetchUp      70          UPI
8  2023-01-12        Food                Chai      15          UPI
9  2023-01-15  Essentials      Salt and Sugar      50         Cash
10 2023-01-17     Grocery           Chocolate     100          UPI
11 2023-01-17        Food          Restaurant     780         Card
12 2023-01-18  Essentials            Food Oil     120          UPI
13 2023-01-18        Food              Zomato     230          UPI
14 2023-01-19     Grocery                Milk      26          UPI
15 2023-01-20  Essentials             Shampoo     780          UPI
16 2023-01-20  Essentials           Lunch Box     890         Cash
17 2023-01-21     Clothes               Dress    1000         Card
18 2023-01-22     Clothes               Dress    1890          UPI
19 2023-01-23     Grocery      Bread and Milk      56         Cash
20 2023-01-24        Food  Fruits and Veggies     530         Cash
21 2023-01-26        Food                Chai      10          UPI
22 2023-01-26     Grocery               Maggi     140          UPI
23 2023-01-27        Food              Zomato     300          UPI
24 2023-01-27        Food                Chai      10          UPI
25 2023-01-28  Essentials           Bedsheets    1025         Cash
26 2023-01-29       Bills             Mobile     1650          UPI
27 2023-01-29     Grocery                Daal     150         Cash
28 2023-01-30       Bills            Cylinder    1074          UPI

In [4]:
# Find the total expense of each category

exp.groupby("Category")['Amount'].sum() #M1
exp.groupby("Category")['Amount'].agg(['sum']) #M2

              sum
Category
Bills       18724
Clothes      2890
Essentials   4485
Food         3022
Grocery      1028

In [5]:
# give a complete expense summary for each category

exp.groupby("Category")['Amount'].agg(['sum','count','mean','max','min'])

              sum  count         mean    max   min
Category
Bills       18724      3  6241.333333  16000  1074
Clothes      2890      2  1445.000000   1890  1000
Essentials   4485      7   640.714286   1500    50
Food         3022      9   335.777778    890    10
Grocery      1028      8   128.500000    456    26

In [8]:
# How much money was paid by each payment method

exp.groupby("Payment Mode")['Amount'].agg(['sum'])

                sum
Payment Mode
Card          17780
Cash           4944
UPI            7425

In [9]:
# How many transactions were made by each payment mode
exp.groupby("Payment Mode")['Amount'].agg(['count'])

              count
Payment Mode
Card              3
Cash             10
UPI              16

In [10]:
# For each payment mode, calculate the total amount spent across categories
exp.groupby(['Payment Mode','Category'])['Amount'].agg(['sum','count'])

                           sum  count
Payment Mode Category
Card         Bills       16000      1
             Clothes      1000      1
             Food          780      1
Cash         Essentials   3465      4
             Food          787      2
             Grocery       692      4
UPI          Bills        2724      2
             Clothes      1890      1
             Essentials   1020      3
             Food         1455      6
             Grocery       336      4

In [11]:
# Which category have the highest total expenses

exp.groupby("Category")['Amount'].sum().sort_values(ascending=False)

Category
Bills         18724
Essentials     4485
Food           3022
Clothes        2890
Grocery        1028
Name: Amount, dtype: int64

In [ ]:
#---------------Task-----------------------
# Create a DataFrame containing the total expense of each category.

total_expense = exp.groupby("Category")['Amount'].sum()
total_expense
# What is the average transaction amount for each payment mode?
# Find the highest individual transaction in each category
# Show total, average, minimum and maximum transaction amount for each payment mode.

### MergeOrJoin

In [13]:
customer = pd.read_csv('subdata_pandas/customer.csv')
customer
payment = pd.read_csv('subdata_pandas/payment.csv')
payment

   customerid  amount            mode paymentdate
0           1      60            Cash  2020-09-24
1          11      80            Cash  2021-03-01
2           2     500     Credit Card  2020-04-27
3           8     100            Cash  2021-01-26
4           7      20  Mobile Payment  2021-02-01
5          17     250     Credit Card  2021-04-01
6          10      70  Mobile Payment  2021-02-28

In [14]:
#Inner Join

pd.merge(left=customer, right=payment,on='customerid',how='inner')

   customerid firstname lastname address  amount         mode paymentdate
0           1      Mary    Smith   Delhi      60         Cash  2020-09-24
1           2     Madan    Mohan  Mumbai     500  Credit Card  2020-04-27
2          17         R   Madhav     Goa     250  Credit Card  2021-04-01

In [15]:
#Left Join

pd.merge(left=customer, right=payment,on='customerid',how='left')

   customerid firstname  lastname  address  amount         mode paymentdate
0           1      Mary     Smith    Delhi    60.0         Cash  2020-09-24
1           3     Linda  Williams    Udupi     NaN          NaN         NaN
2           4   Barbara     Jones  Chennai     NaN          NaN         NaN
3           2     Madan     Mohan   Mumbai   500.0  Credit Card  2020-04-27
4          17         R    Madhav      Goa   250.0  Credit Card  2021-04-01

In [16]:
#Right Join

pd.merge(left=customer, right=payment,on='customerid',how='right')

   customerid firstname lastname address  amount            mode paymentdate
0           1      Mary    Smith   Delhi      60            Cash  2020-09-24
1          11       NaN      NaN     NaN      80            Cash  2021-03-01
2           2     Madan    Mohan  Mumbai     500     Credit Card  2020-04-27
3           8       NaN      NaN     NaN     100            Cash  2021-01-26
4           7       NaN      NaN     NaN      20  Mobile Payment  2021-02-01
5          17         R   Madhav     Goa     250     Credit Card  2021-04-01
6          10       NaN      NaN     NaN      70  Mobile Payment  2021-02-28

In [20]:
#Cross Join

pd.merge(left=customer, right=payment, how='cross')

,customerid_x,firstname,lastname,address,customerid_y,amount,mode,paymentdate
0,1,Mary,Smith,Delhi,1,60,Cash,2020-09-24
1,1,Mary,Smith,Delhi,11,80,Cash,2021-03-01
2,1,Mary,Smith,Delhi,2,500,Credit Card,2020-04-27
3,1,Mary,Smith,Delhi,8,100,Cash,2021-01-26
4,1,Mary,Smith,Delhi,7,20,Mobile Payment,2021-02-01
5,1,Mary,Smith,Delhi,17,250,Credit Card,2021-04-01
6,1,Mary,Smith,Delhi,10,70,Mobile Payment,2021-02-28
7,3,Linda,Williams,Udupi,1,60,Cash,2020-09-24
8,3,Linda,Williams,Udupi,11,80,Cash,2021-03-01
9,3,Linda,Williams,Udupi,2,500,Credit Card,2020-04-27
10,3,Linda,Williams,Udupi,8,100,Cash,2021-01-26
11,3,Linda,Williams,Udupi,7,20,Mobile Payment,2021-02-01
12,3,Linda,Williams,Udupi,17,250,Credit Card,2021-04-01
13,3,Linda,Williams,Udupi,10,70,Mobile Payment,2021-02-28
14,4,Barbara,Jones,Chennai,1,60,Cash,2020-09-24
15,4,Barbara,Jones,Chennai,11,80,Cash,2021-03-01
16,4,Barbara,Jones,Chennai,2,500,Credit Card,2020-04-27
17,4,Barbara,Jones,Chennai,8,100,Cash,2021-01-26
18,4,Barbara,Jones,Chennai,7,20,Mobile Payment,2021-02-01
19,4,Barbara,Jones,Chennai,17,250,Credit Card,2021-04-01
20,4,Barbara,Jones,Chennai,10,70,Mobile Payment,2021-02-28
21,2,Madan,Mohan,Mumbai,1,60,Cash,2020-09-24
22,2,Madan,Mohan,Mumbai,11,80,Cash,2021-03-01
23,2,Madan,Mohan,Mumbai,2,500,Credit Card,2020-04-27
24,2,Madan,Mohan,Mumbai,8,100,Cash,2021-01-26
25,2,Madan,Mohan,Mumbai,7,20,Mobile Payment,2021-02-01
26,2,Madan,Mohan,Mumbai,17,250,Credit Card,2021-04-01
27,2,Madan,Mohan,Mumbai,10,70,Mobile Payment,2021-02-28
28,17,R,Madhav,Goa,1,60,Cash,2020-09-24
29,17,R,Madhav,Goa,11,80,Cash,2021-03-01
30,17,R,Madhav,Goa,2,500,Credit Card,2020-04-27
31,17,R,Madhav,Goa,8,100,Cash,2021-01-26
32,17,R,Madhav,Goa,7,20,Mobile Payment,2021-02-01
33,17,R,Madhav,Goa,17,250,Credit Card,2021-04-01
34,17,R,Madhav,Goa,10,70,Mobile Payment,2021-02-28